# Generated by Django 5.1.7 on 2025-03-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaluser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
